{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "opencodehub.fullname" . }}
  labels:
    {{- include "opencodehub.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "opencodehub.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
{{- end }}
