apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencodehub.fullname" . }}
  labels:
    {{- include "opencodehub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "opencodehub.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
